Greeting.create(:message => "Test message 1")
Greeting.create(:message => "Test message 2")
Greeting.create(:message => "Test message 3")
Greeting.create(:message => "Test message 4")
Greeting.create(:message => "Test message 5")
